---
title: "Graphical parameters in R with par(): With great power comes great responsibility"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Graphical parameters in R with par(): With great power comes great responsibility}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval = T}
library(compbio4all)
```




## Save plotting defaults

```{r}
par_defaults <- par()
```


## Data

```{r}
census <- 1:39
year.t   <- 1959:1997
females.N <- c(44,47,46,44,46,
               45,46,40,39,39,
               42,39,41,40,33,
               36,34,39,35,34,
               38,36,37,41,39,
               51,47,57,48,60,
               65,74,69,65,57,
               70,81,99,99)
lambda.i <- females.N[-1]/females.N[-length(females.N)]
lambda.i <- c(lambda.i,NA)
lambda_log <- log(lambda.i)
bear_N <- data.frame(census,
                year.t,
                females.N,
                lambda.i, 
                lambda_log)
```



## A single-panel plot - default

```{r}

plot(females.N ~ year.t, data = bear_N)

```


## A single-panel plot - explicitly with par()

```{r}
par(mfrow = c(1,1))
plot(females.N ~ year.t, data = bear_N)

```


## A vertical 2-panel plot -  with par()

TODO doen'st like to knit

```{r eval = F}
par(mfrow = c(2,1))

plot(lambda_log ~ females.N, data = bear_N)
plot(females.N ~ year.t, data = bear_N)

```


## A horizontal 2-panel plot -  with par()

```{r}
par(mfrow = c(1,2))

plot(lambda_log ~ females.N, data = bear_N)
plot(females.N ~ year.t, data = bear_N)

```




## A 4-panel plot -  with par()

TODO doesn't like to knot
```{r eval = F}
par(mfrow = c(2,2))

plot(lambda_log ~ females.N, data = bear_N)
plot(females.N ~ year.t, data = bear_N)

```


## A horizontal 2-panel plot -  with par() and adjusted margins

```{r}
par(mfrow = c(1,2), mar = c(4,4,1,1))

plot(lambda_log ~ females.N, data = bear_N)
plot(females.N ~ year.t, data = bear_N)

```


## Reset defaults

This fails - why
```{r eval = F}
par(par_defaults)
```


