---
title: "A primer of population ecology: Part 3 - Basic population models"
author: "Nathan Brouwer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A primer of population ecology: Part 3 - Basic population models}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval  = F,
  comment = "#>"
)

N <- c(432,502,201,200,216,167,179,200,219,200,211,243,232,207,215,215,216,210,167,207,212,265,347, 397,485,633,765,692,728,804,904,891,1085,1050,1202,1341,1420,1485,1707,1803,1826,1773,1828,2090,2020, NA,2365,
       1023/0.40)

year <- c(1951,1961,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,
          1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,
          2001,2002,2003,2004,2005,2006, 2007,2008,2009,2010,2011,2012,2013,2014,2015,
          2019)
```






## Basic mathematical models can be built using algebra

The term **mathematical model** perhaps sounds fancy, but in many of their forms these are just equations manipulated using standard algebra to allow us to think about how populations change.  

Here's some examples of the level of math needed to get started working with population models. Most people learned this equation in high school

$y = M*x + B$

In math class, we call this an **equation** that tells us the relationship between the variables x and y.  In biology, we'd call this a **mathematical model** that allows us to predict y if we know x.

Using the above above equation, if  I tell you M = 1.2 and B = 10, can you calculate what y is when x = 10?

TODO: make a practice version of this problem

M and B are the **parameters** in this model.  We can plug them into the equation:

$y = 1.2*x + 10$

We can then calculate y:

$y = 1.2*10 + 10$
$y = 12 + 10$
$y = 22$

What if I told you y was 220, x was 100, and B was 10 - how would you calculate what M was?  We could start like this with our known parameter (b = 10) and our values for x and y:

TODO: make a practice version of this problem


$220 = m*100 + 10$

We then do some algebra.  First deal with the 10:

$220 - 10 = M*100 + 10 - 10$

This gives us:
$210 = M*100$

Now divide both sides by 100.  First do the right-hand side:

$\frac{210}{100} = \frac{M*100}{100}$

Which gives us
$\frac{210}{100} = M$

Then divide 210 by 100:

$2.1 = M$

The math behind basic population models is not much more involved than this.


## Population dynamics can be described with mathematical models

We can write equations to describe changes in populations (**population dynamics**), calling the number of organisms right now $N_{now}$ and the number next year $N_{next.year}$.

Populations change due to processes such as the deaths of current members of the population and the birth of offspring.  We can write out how a population change like this

$N_{next.year}= N_{now} - N_{died.this.year} + N_{born.this.year}$

When we write equations like this, we always need to remember that they represent an *idealized* situation; rarely can we know how large a population currently is (*N_{now}*), and its even harder to determine exactly how many died or were born in a given year.  

In addition to births and deaths, populations can also be increase due to **immigration**, and decrease due to **emigration**. We therefore expand our idealized equation to be:

$N_{next.year}= N_{now} - N_{died.this.year} + N_{born.this.year} - N_{immigrant}+N_{emmigrant}$

To make these equations more compact we often write using a more succinct notation, where a **subscript** of "t" = a certain time, and "t+1" equals the following time period.  Usually this **time step** is one year, but it could be any period of time relevant to the biology of an organism.  

Using subscripts we can re-write our equation as:

$N_{t+1}= N_{t} - N_{died.t} + N_{born.t} - N_{immigrant.t}+N_{emmigrant.t}$

where 

$N_{t+1} = N_{next.year}$

and 

$N_{t} = N_{now}$

Often births and deaths are given their own symbols, **B** and **D**, as are immigration (**I**) and emigration (**E**):

$N_{t+1}= N_{t} - D + B - I + E$

Different authors and text books unfortunately use different notation, so its important that everyone is clear what all their symbols mean, and that readers carefully determine what the symbols mean.  In this case, it needs to be emphasized that N, D, B, I and E *all* represent absolute numbers of individuals - they are meant to represent counts of organism, not rates.  For example, just as  $N_{t}$ is a count of all the individuals in the population and must be a whole number like 1010, B is a count of the number of births and must be a whole number like 500.  

Its useful to remember that when you're working with addition and subtraction you can move terms around in the equation and not alter the math.  So our previous equation can be changed to this by moving around the order of the terms:

$N_{t+1}= N_{t} + B - D + E - I$

Similarly, we can add parentheses to help us organize things without changing the meaning.  In the equation below, number of births (B) and deaths (D) are grouped because these are opposing processes; similarly we group E (emigration ) and I (immigration).  Again, this does nothing to change the meaning.

$N_{t+1}= N_{t} + B - D + E - I$

I can state the fact that these two equations are identical like this: 

$N_{t} + B - D + E - I = N_{t} + B - D + E - I$


## Immigration and emigration are hard to study

Immigration and emigration are complicated processes to study.  Most populations are **open** to some degree, especially **animals**.  The only exceptions to this are oceanic islands that are distant from the mainland and other isolate chunks of habitat. Many habitats do have fairly rare rates of immigration, such as most islands, lakes, and isolated **fragments** of habitat that are surrounded by inhospitable conditions such as human structures.   For example, Abuko Nature Preserve in The Gambia, West Africa is surrounded on all sides by the suburbs of the capitol, Banjul.  Except for some birds, all animals born in Abuko will live their whole lives their and never leave.  When habitats are isolated like this,  **dispersal events** are  so rare that they can be ignored.  

Research on populations where immigration and emigration are minimal is convenient.  This allows us to simplify our model of population dynamics from 

$N_{t+1}= N_{t} + B - D + E - I$

to one without E and I:

$N_{t+1}= N_{t} + B - D$


## We often frame population dynamics in terms of the amount of change

Often our equation of population dynamics gets converted from focusing on the number of individuals (N.t, N.t+1) to the change in the number of individuals.  We can make this alteration to our equation algebraically by subtracting $N_{t}$ from both sides of our equation

Our equation was:
$N_{t+1} = N_{t} + B - D$

We subtract N.t
$N_{t+1} - N_{t} = N_{t} + B - D - N_{t}$

Rearrange terms for simplicity
$N_{t+1} - N_{t} = B - D + N_{t}- N_{t}$

Then simplify:
$N_{t+1} - N_{t} = B - D$

$N_{t+1} - N_{t}$ is usually written as $\Delta N$, where $\Delta$ is the Greek letter, Delta, which is used throughout science to mean change.

$\Delta N = B - D$

When B > D, $\Delta N$ is positive and the population got bigger.  When B < D, $\Delta N$ is negative and the population got smaller.  If $\Delta N$ = 0, then births were balanced out by deaths and the population has not changed.  

This all looks fairly simple but is actually kind of profound: you can ignore how large a population actually is and still know about its population dynamics by keeping track of just births and deaths.  Conversely, if you know how much a population has changed in size, you can know whether there were more births than deaths, or if deaths exceed births.

