---
title: "A primer of population ecology: Part 1 - What is population ecology?"
author: "Nathan Brouwer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A primer of population ecology: Part 1 - What is population ecology?}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval  = F,
  comment = "#>"
)
```



## Key vocab

Put key vocab here

## Population ecology is the science of population dynamics

**Ecology** is often described generally as the study of the **distribution and abundance** of organisms.  A major interest in ecology is the patterns and processes of changes in the abundance organisms in a **population** over time.  These patterns can be considered in terms of 

1. **Size**: How many individuals there are.
1. **Density**: How many individuals per unit of area.
1. **Occupancy**: Whether a species occurs in a given habitat or not.
1. **Population extent**: Where a population occurs in space.
1. **Species range**: Where an entire species occurs in space

## Populations can be described by their size, density, or spatial extent.

### Population size is the actual number of indiviudals in a population

**Population size** is the actual number of organisms in a population.  This is often of great interest to biologists -- especially those interested in forestry, wildlife management and conservation -- and most of our basic population models work with population sizes.  However, this is often an very difficult quantity to determine.  Only if a **complete census** is carried out and every individual can be definitivly accounted for can be be sure about the actual population size.  In most cases we can only attempt to estimate the population size (N) using well designed field studies and statistics.  Indeed, some population ecologists specialize in developing mathematical and statistical models to accurately estimate population size.   Often, however, we don't even have good estimates and only have crude approximations, such as the number of animals harvested by hunters or trapped by ecologists.  In the following lessons will occassionally use these so-called **proxies** for population size because they are common in the ecological literature.  These approximations have often been shown to bep prone to bias and inacciracies, prompting increasing developement of study designs and statistics to accurarelty estimate population size itslef.

When species become **endangered** researchers often try to determine - or at least estimate - the **extant** number of individuals surviving.  For example, in North American Kirkland's Warbler isthe rarest soecies breeding in the continental United States was considered critically endangered throughout most of the 20th century.  Researchers therefore worked each spring to determine as best as possible how many male warblers had established territories and were trying to attract mates.

**Population density** is how many individuals occur in a given area of space.  For animals and trees, this is often the estimated number of animals per hectare (a hectare is 100 m by 100 m, or 2.47 acres)  For plants, insects, and other smaller organisms this is often the number per square meter. 

Kirkland's Warbler is a **habitat specialist** and only nests in stands of a single tree, the Jack Pine.  Moreover, it only nests in Jack Pines of a certain age and density: between 1200—4000 pines per hectare.  

**Species occupancy** is simply whether a given species occurs in a habitat patch, fragment, or area.  Often it can be very difficult to count the number of individuals or determine their density; instead of asking a question like "how many owls are in there in this forest" its relatively easier to ask "are there *any* owls in this forest."  It can be very time consuming to do counts or determine density, which can limit researchers ability to study multiple sites or locations.  Focusing on **occupancy** often allows researchers to study a larger area.

Kirkland's Warbler is currently increasing its **population size** and its being found in stands of Jack Pine outside of Michigan.  Since the warbler's population is increasing, researchers are more interested in doing **occupancy surveys** to determine which forests warblers are occurring in rather than determining exactly how many warblers are in these forests.

**Population extent** is the geographic area where a population occurs.  Some populations occur on islands, in lakes, or in distinct **habitat fragments** such as forests surrounded by farms and are geographically isolated from other populations of the same species.  Other species are **habitat specialists** and only occur in specific places where a certain type of ecosystem occurs.  For example, some animals only nest in very old trees and so their **old growth** habitat may occur in isolated patches separated by younger parts of a forest.

The Spotted Owl is a **habitat specialist** that only occurs in **old growth forests** in the Pacific Northwest (British Columbia, Washington, Oregon, California).  Much of the Pacific Northwest is forests, but most stands are less than 100 years old and don't have the large, old trees that the owls nest in.  The extant of each population of owls is therefore limited by the size of each patch of old growth forest.

**Species range** is the total geographic area occupied by a species.  For example, bald eagles occur all throughout North America, while Golden Eagles only occur in the eastern united states.

Kirkland's warbler only occur in the Jack Pine Forests of Michigan and a few adjacent states and Canadian provinces.  It therefore as a very restricted range.  Because its range is so small there is basically a single population, so the population extent and species range are essentially the same.


